config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.from_plugin APP_CONFIG[:app_name] + "_engine" if APP_CONFIG[:use_engine_plugin]
  
  #Restful Authentication
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.activate '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil
  map.forgot_password '/forgot_password', :controller => 'passwords', :action => 'new'
  map.change_password '/change_password/:reset_code', :controller => 'passwords', :action => 'reset'
  
  map.resource :session
  map.resources :users, :passwords, :roles, :images, :documents
  map.resources :comments, :collection => { :destroy_multiple => :delete},
                :member => { :approve => :put, :reject => :put }
  map.resources :pages do |page|
    page.resources :components, :name_prefix => nil
    page.resources :articles, :name_prefix => nil, :as => "content"
    page.resources :newsitems, :name_prefix => nil, :as => "latest", :collection => {:archive => :get}
    page.resources :posts, :name_prefix => nil, :as => "posts", :collection => {:archive => :get}
    page.resources :events, :name_prefix => nil, :as => "list"
  end
  
  # Search
  map.search 'search', :controller => "search", :action => "index"
  
  # Calendar Mapping
  map.browse 'pages/:page_id/browse/:month/:year', :controller => 'events', :action => 'index'
  
  # News Archive Mapping
  map.archive 'pages/:page_id/archive/:month/:year', :controller => 'newsitems', :action => 'archive'
  map.annual_archive 'pages/:page_id/archive/:year', :controller => 'newsitems', :action => 'archive'
  
  # Blog Archive Mapping
  map.blog_archive 'pages/:page_id/archived/:month/:year', :controller => 'posts', :action => 'archive'
  map.blog_annual_archive 'pages/:page_id/archived/:year', :controller => 'posts', :action => 'archive'

  map.home "", :controller => "articles", :page_id => "1"
  map.root :home
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :page
  acts_as_list :scope => :page
  has_many :images
  has_many :documents
  acts_as_indexed :fields => [:title, :content]
  validates_presence_of :title
  
  # Strip any speech marks and replace with a marker
  def before_save
    self.content = content.gsub(/["]/, '[s-mark]') unless content.nil?
  end
  
  def sortable?
    true
  end
  
  def parsed_video
    @parsed_video ||= video.gsub('watch?v=','v/')
  end
  
  def to_param
    "#{id}-#{permalink}" unless id.nil?
  end
  
  def permalink
    title.downcase.gsub(/[^a-z1-9]+/i, '-') unless title.nil?
  end
  
  def component_preview
    if article_type == "documents"
      "Preview not available..."
    else
      content.slice(0, 100) + "..."
    end
  end
  
  IMAGESIZE = [
    [ 'Small', 'thumb100' ],
    [ 'Regular', 'thumb200' ],
    [ 'Medium', 'thumb300' ],
    [ 'Large', 'thumb400' ]
  ]
  
  # For the news and blog archive sections
  def self.find_all_in_month(year, month, page_params, page)
    conditions = ["page_id = ? AND created_at BETWEEN ? AND ?", page.id, DateTime.new(year, month, 1), DateTime.new(year, month, days_in_month(year, month), 11, 59, 59)]
    self.paginate(:page => page_params, :per_page => page.paginate, :conditions => conditions, :order => "created_at DESC")
  end
  
  def self.find_all_in_year(year, page_params, page)
    conditions =  ["page_id = ? AND created_at BETWEEN ? AND ?", page.id, DateTime.new(year, 1, 1), DateTime.new(year, 12, 31, 11, 59, 59)]
    self.paginate(:page => page_params, :per_page => page.paginate, :conditions => conditions, :order => "created_at DESC")
  end
  
  def self.archive_links(page)
    self.find(:all, :select => "created_at", :conditions => ["page_id = ?", page.id]).group_by {|a| a.created_at.strftime('%Y')}.sort.reverse
  end
  
  private

  def self.days_in_month(year, month)
    Date.new(year, month, -1).day
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  caches_action :index,
                :unless => :logged_in?, 
                :cache_path => Proc.new { |c| c.params[:page_id] } 
                
  cache_sweeper :article_sweeper, :only => [:create, :update, :destroy]
  
  before_filter :login_required, :except => [:index, :show, :archive]
  before_filter :get_page, :only => [:index, :new, :edit, :show, :archive]
  before_filter :check_view_rights, :only => [:index]
  before_filter :check_edit_rights, :only => [:new, :edit]
  
  def index
    @articles = @page.articles.paginate(:page => params[:page], :per_page => @page.paginate)
    if @page.id == 1
      render :template => "homepage/index"
    end
  end

  def new
    @article = Article.new(:page_id => params[:page_id])
    @images = []
  end

  def edit
    @article = Article.find(params[:id])
    @images = @article.images
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      flash[:notice] = "#{@article.article_type.capitalize} was successfully created"
      redirect_to resource_index_page(@article)
    else
      @images = @article.images
      get_page
      render :action => "new" 
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      flash[:notice] = "#{@article.article_type.capitalize} was successfully updated"
      redirect_to resource_index_page(@article)
    else
      @images = @article.images
      get_page
      render :action => "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to resource_index_page(@article)
  end
  
  private 
  
  def resource_index_page(resource)
    if resource.article_type == "post"
      posts_path(resource.page_id) 
    elsif resource.article_type == "news"
      newsitems_path(resource.page_id) 
    else
      articles_path(resource.page_id) 
    end
  end
  
end

app/views/articles/_article.html.erb
<div class="span-12">
  <% form_for(@article, :url => article_path(@page, @article), :html => {:class => "seed-admin tight", :id => "changer"}) do |f| %>
    <%= f.error_messages %>
    <div id="fieldset">
    <div class="input-row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div id="image-size-options">
    <% if !@article.images.empty? %>
    	<%= render :partial => "image_size_options" %>
    <% end -%>
    </div>
    <div class="input-row">
      <%= f.label :content %>
      <%= display_speech_marks(f.text_area :content) %>
    </div>
    </div>
    <%= f.hidden_field :page_id %>
    <%= hidden_field :article, :article_type, {:value => "article"} %>
    <div id="image-ids" class="submit">
  	<% @article.images.each do |image| %>
  		<%= hidden_field_tag "article[image_ids][]", image.id, :id => "hidden_image_tag_#{image.id}" %>
  	<% end -%>
      <%= f.submit "#{submit}" %> or <%= link_to_function 'cancel', 'history.go(-1)' %>
    </div>
  <% end %>
</div>

<div class="span-5">
	<div id="seed-notes">
		<h4>Post Style:</h4>
		<h5>Article</h5>
		<p>General purpose post containing text and images.</p> 
	</div>
	
	<div id="image-control">
		<%= link_to_lightview( "Add Image",
				new_image_path, 
				{:class => "add"}, {:title => "'Image Upload'"}, {:autosize => false, :width => 400, :height => 250} )%>
		<div id="image-list">
			<%= render :partial => "images/image_item", :collection => @images %>
		</div>
	</div>
</div>

app/views/articles/_documents.html.erb
<div class="span-12">
  <% form_for(@article, :url => article_path(@page, @article), :html => {:class => "seed-admin tight", :id => "changer"}) do |f| %>
    <%= f.error_messages %>
    <div id="fieldset">
    <div class="input-row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="input-row">
      <%= f.label :content %>
      <%= f.text_area :content, :class => "compact" %>
    </div>
    </div>
    <div id="document-ids">
  	  <% @article.documents.each do |document| %>
  		  <%= hidden_field_tag "article[document_ids][]", document.id, :id => "hidden_document_tag_#{document.id}" %>
  	  <% end -%>
    </div>
    <%= f.hidden_field :page_id %>
    <%= hidden_field :article, :article_type, {:value => "documents"} %>
    <%= f.submit "#{submit}" %> or <%= link_to_function 'cancel', 'history.go(-1)' %>
  <% end %>
</div>

<div class="span-5">
	<div id="seed-notes">
		<h4>Component Type:</h4>
		<h5>Documents</h5>
		<p>Displays links to documents for viewing or download.</p> 
		<p>Upload documents that you would like this article to display.</p>
	</div>
</div>

<div id="form-documents" class="span-17">
  
		<%= link_to_lightview( "Upload Document", new_document_path(:for => "article"), 
				{:class => "button"}, {:title => "'Document Upload'"}, {:autosize => false, :width => 400, :height => 300} )%>
		
		<table id="document-table" class="seed-admin">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Type</th>
		      <th>Filename</th>
		      <th colspan="2">Size</th>
		    </tr>
		  </thead>
		  <tbody>
        <%= render :partial => "documents/document", :collection => @article.documents %>
		  </tbody>
		</table>
		
</div>

app/views/articles/_image_size_options.html.erb
<div class="input-row" id="image-size-partial">
  <%= label :article, :imagesize, "Image Display Size" %>
  <%= select(:article, :imagesize, Article::IMAGESIZE) %>
</div>

app/views/articles/_table.html.erb
<div class="span-12">
  <% form_for(@article, :url => article_path(@page, @article), :html => {:class => "seed-admin tight", :id => "changer"}) do |f| %>
    <%= f.error_messages %>
    <div id="fieldset">
    <div class="input-row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="input-row">
      <%= f.label :content, "Table Data" %>
      <%= display_speech_marks(f.text_area :content) %>
    </div>
    </div>
    <div class="submit">
  	<%= f.hidden_field :page_id %>
  	<%= hidden_field :article, :article_type, {:value => "table"} %>
      <%= f.submit "#{submit}" %> or <%= link_to_function 'cancel', 'history.go(-1)' %>
    </div>
  <% end %>
</div>

<div class="span-5">
	<div id="seed-notes">
		<h4>Post Style:</h4>
		<h5>Table</h5>
		<p>Create a table by entering special field separators between the data that you wish to tabulate.</p> 
		<p>Use a | to separate columns.</p>
		<p>Start a new line for each new row.</p>
		<p>| age | sex |</p>
		<p>| 43 | male |</p>
		<p>Have a look at the <a href="">markup guide</a> for more complex table options.</p>
	</div>
</div>

app/views/articles/_video.html.erb
<div class="span-12">
  <% form_for(@article, :url => article_path(@page, @article), :html => {:class => "seed-admin tight", :id => "changer"}) do |f| %>
    <%= f.error_messages %>
    <div id="fieldset">
    <div class="input-row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="input-row">
      <%= f.label :video, "Video URL" %>
      <%= f.text_field :video %>
    </div>
    <p><small>Currently only works with YouTube.<br />(ie. http://youtube.com/watch?v=5cGvqs-jf_w)</small></p>
    <div class="input-row">
      <%= f.label :content, "Caption" %>
      <%= display_speech_marks(f.text_area :content, :class => "compact") %>
    </div>
    </div>
    <div class="submit">
  	<%= f.hidden_field :page_id %>
  	<%= hidden_field :article, :article_type, {:value => "video"} %>
      <%= f.submit "#{submit}" %> or <%= link_to_function 'cancel', 'history.go(-1)' %>
    </div>
  <% end %>
</div>

<div class="span-5">
	<div id="seed-notes">
		<h4>Post Style:</h4>
		<h5>Video</h5>
		<p>Entering a video URL from sites like YouTube or Vimeo will display video inside your article.</p> 
		<p>You can also enter a title for the video and caption.</p>
	</div>
</div>

app/views/articles/edit.html.erb
<div id="seed-admin-form">
  <h2 class="admin">Edit article</h2>
  
  <ul id="formtabs">
  	<li class="articletab"><%= form_tab_link "Article", "Update", @article %></li>
  	<li class="videotab"><%= form_tab_link "Video", "Update", @article %></li>
  	<li class="tabletab"><%= form_tab_link "Table", "Update", @article %></li>
  	<li class="documentstab"><%= form_tab_link "Documents", "Update", @article %></li>
  </ul>
  <div id="tabbedform">
  	<%= render :partial => @article.article_type, :locals => {:submit => "Update"} %>
  </div>
</div>

app/views/articles/index.html.erb
<% if @page.requires_sidebar? %>
  <div class="span-14 colborder">
    <%= seed_render_all @articles, "articles" %>
    <%= will_paginate @articles %>
  </div>
  <div class="span-4 last">
    <%= seed_page_components %>
    <ul><%= seed_flat_child_links(@page) %></ul>
  </div>

<% else -%>
  <%= seed_render_all @articles, "articles" %>
  <%= will_paginate @articles %>
<% end -%>

app/views/articles/new.html.erb
<div id="seed-admin-form">
	<h2 class="admin">New article</h2>
	
	<ul id="formtabs">
		<li class="articletab"><%= form_tab_link "Article", "Create", "selected" %></li>
		<li class="videotab"><%= form_tab_link "Video", "Create" %></li>
		<li class="tabletab"><%= form_tab_link "Table", "Create" %></li>
		<li class="documentstab"><%= form_tab_link "Documents", "Create" %></li>
	</ul>
	<div id="tabbedform">
		<%= render :partial => "article", :locals => {:submit => "Create"} %>
	</div>
</div>