config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.from_plugin APP_CONFIG[:app_name] + "_engine" if APP_CONFIG[:use_engine_plugin]
  
  #Restful Authentication
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.activate '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil
  map.forgot_password '/forgot_password', :controller => 'passwords', :action => 'new'
  map.change_password '/change_password/:reset_code', :controller => 'passwords', :action => 'reset'
  
  map.resource :session
  map.resources :users, :passwords, :roles, :images, :documents
  map.resources :comments, :collection => { :destroy_multiple => :delete},
                :member => { :approve => :put, :reject => :put }
  map.resources :pages do |page|
    page.resources :components, :name_prefix => nil
    page.resources :articles, :name_prefix => nil, :as => "content"
    page.resources :newsitems, :name_prefix => nil, :as => "latest", :collection => {:archive => :get}
    page.resources :posts, :name_prefix => nil, :as => "posts", :collection => {:archive => :get}
    page.resources :events, :name_prefix => nil, :as => "list"
  end
  
  # Search
  map.search 'search', :controller => "search", :action => "index"
  
  # Calendar Mapping
  map.browse 'pages/:page_id/browse/:month/:year', :controller => 'events', :action => 'index'
  
  # News Archive Mapping
  map.archive 'pages/:page_id/archive/:month/:year', :controller => 'newsitems', :action => 'archive'
  map.annual_archive 'pages/:page_id/archive/:year', :controller => 'newsitems', :action => 'archive'
  
  # Blog Archive Mapping
  map.blog_archive 'pages/:page_id/archived/:month/:year', :controller => 'posts', :action => 'archive'
  map.blog_annual_archive 'pages/:page_id/archived/:year', :controller => 'posts', :action => 'archive'

  map.home "", :controller => "articles", :page_id => "1"
  map.root :home
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :page
  acts_as_list :scope => :page
  has_many :images
  has_many :documents
  acts_as_indexed :fields => [:title, :content]
  validates_presence_of :title
  
  # Strip any speech marks and replace with a marker
  def before_save
    self.content = content.gsub(/["]/, '[s-mark]') unless content.nil?
  end
  
  def sortable?
    true
  end
  
  def parsed_video
    @parsed_video ||= video.gsub('watch?v=','v/')
  end
  
  def to_param
    "#{id}-#{permalink}" unless id.nil?
  end
  
  def permalink
    title.downcase.gsub(/[^a-z1-9]+/i, '-') unless title.nil?
  end
  
  def component_preview
    if article_type == "documents"
      "Preview not available..."
    else
      content.slice(0, 100) + "..."
    end
  end
  
  IMAGESIZE = [
    [ 'Small', 'thumb100' ],
    [ 'Regular', 'thumb200' ],
    [ 'Medium', 'thumb300' ],
    [ 'Large', 'thumb400' ]
  ]
  
  # For the news and blog archive sections
  def self.find_all_in_month(year, month, page_params, page)
    conditions = ["page_id = ? AND created_at BETWEEN ? AND ?", page.id, DateTime.new(year, month, 1), DateTime.new(year, month, days_in_month(year, month), 11, 59, 59)]
    self.paginate(:page => page_params, :per_page => page.paginate, :conditions => conditions, :order => "created_at DESC")
  end
  
  def self.find_all_in_year(year, page_params, page)
    conditions =  ["page_id = ? AND created_at BETWEEN ? AND ?", page.id, DateTime.new(year, 1, 1), DateTime.new(year, 12, 31, 11, 59, 59)]
    self.paginate(:page => page_params, :per_page => page.paginate, :conditions => conditions, :order => "created_at DESC")
  end
  
  def self.archive_links(page)
    self.find(:all, :select => "created_at", :conditions => ["page_id = ?", page.id]).group_by {|a| a.created_at.strftime('%Y')}.sort.reverse
  end
  
  private

  def self.days_in_month(year, month)
    Date.new(year, month, -1).day
  end
  
end

app/models/post.rb
# Blog Posts
class Post < Article
  # TODO Handle periodic cleaning of old un-approved comments
  has_many :comments
  
  def self.find(*args)
    with_scope(:find=> { :conditions=> "article_type = 'post'" } ) do
      super(*args)
    end
  end
  
  def sortable?
    false
  end
  
end

app/controllers/posts_controller.rb
# Blog Posts Controller
class PostsController < ArticlesController
  
  caches_action :show,
                :unless => :logged_in?, 
                :if => Proc.new { |c| c.params[:nocache] == "t"},
                :cache_path => Proc.new { |c| c.params[:id] }
                
  caches_action :archive,
                :unless => :logged_in?, 
                :cache_path => Proc.new { |c| "page-#{c.params[:page_id]}-archive-#{c.params[:year]}#{c.params[:month]}" }
  
  before_filter :check_view_rights, :only => [:show, :archive]
  
  def index
    @posts = @page.posts.paginate(:page => params[:page], :per_page => @page.paginate, :order => "created_at DESC")
  end
  
  def archive
    if params[:month]
      @posts = Post.find_all_in_month(params[:year].to_i, params[:month].to_i, params[:page], @page)
    else
      @posts = Post.find_all_in_year(params[:year].to_i, params[:page], @page)
    end
    render :template => "posts/index"
  end
  
  def show
    @post = @page.posts.find(params[:id])
    if @post.article_type == "post"
      @comment = Comment.new
    end
  end
  
end

app/views/posts/_comment.html.erb
<div class="comment <%= cycle('odd', 'even') %>">
	<% if editable?(@page) -%>
		<span class="seed-admin-tag seed-edit-tag">
			<%= link_to "X", comment_path(comment, :page_id => params[:page_id]), :confirm => 'Delete this comment?', :method => :delete %>
			<%= link_to "spam", reject_comment_path(comment, :page_id => params[:page_id]), :method => :put %>
		</span>
	<% end -%>
	Posted by: <%= link_to_unless(comment.website.blank?, content_tag(:strong, comment.name), comment.website) -%>
	<%= time_ago_in_words(comment.created_at) %> ago
	<%= textilize(comment.comment) %>
</div>

app/views/posts/_commentform.html.erb
<div id="commentform" class="span-12">
	<h3>Add your comment:</h3>
	<% form_for(@comment, :html => {:class => "seed-admin tight comment"}) do |f| %>
		<div class="input-row">
			<%= f.label :name, "Name: <small>(required)</small>" %>
			<%= f.text_field :name %>
		</div>
		<div class="input-row">
			<%= f.label :email, "Email: <small>(not displayed)</small>" %>
			<%= f.text_field :email %>
		</div>
		<div class="input-row">
			<%= f.label :website, "Website URL: <small>(include http://)</small>" %>
			<%= f.text_field :website %>
		</div>
		<div class="input-row">
			<%= f.label :comment, "Comment: <small>(required)</small>" %>
			<%= f.text_area :comment %>
		</div>
		<%= hidden_field_tag :page_id, params[:page_id] %>
		<%= f.hidden_field :post_id, :value => params[:id] %>
		<%= f.submit "Submit" %>
	<% end -%>	
</div>

app/views/posts/_form.html.erb
<div class="span-12">
<% form_for(@article, :url => post_path(@page, @article), :html => {:class => "seed-admin tight"}) do |f| %>
  <%= f.error_messages %>
  <div id="fieldset">
  <div class="input-row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div id="image-size-options">
  <% if !@article.images.empty? %>
  	<%= render :partial => "articles/image_size_options" %>
  <% end -%>
  </div>
  <div class="input-row">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="commentable-row">
    <%= f.label :commentable, "Comments for this post:" %>
    <%= f.radio_button :commentable, true, :style => "display:inline" %>On
    <%= f.radio_button :commentable, false %>Off
  </div>
  </div>
  <%= f.hidden_field :page_id %>
  <%= f.hidden_field :article_type, {:value => "post"} %>
  <%= f.hidden_field :author, {:value => current_user.name} %>

  <div id="image-ids" class="submit">
	<% @article.images.each do |image| %>
		<%= hidden_field_tag "article[image_ids][]", image.id, :id => "hidden_image_tag_#{image.id}" %>
	<% end -%>
    <%= f.submit "#{submit}" %> or <%= link_to_function 'cancel', 'history.go(-1)' %>
  </div>
<% end %>
</div>

<div class="span-5">
	<div id="seed-notes">
		<h4>Post Style:</h4>
		<h5>Blog Post</h5>
		<p>General purpose post containing text and images.</p> 
	</div>
	
	<div id="image-control">
		<%= link_to_lightview( "Add Image",
				new_image_path, 
				{:class => "add"}, {:title => "'Image Upload'"}, {:autosize => false, :width => 400, :height => 250} )%>
		<div id="image-list">
			<%= render :partial => "images/image_item", :collection => @images %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div id="seed-admin-form">
  <h2 class="admin">Edit blog post</h2>
  
  <div id="articlesform">
  	<%= render :partial => "form", :locals => {:submit => "Update"} %>
  </div>
</div>

app/views/posts/index.html.erb
<div id="blog" class="span-14 colborder">
  <%= seed_render_all @posts, "blogposts" %>
	
	<%= will_paginate @posts %>
	
</div>
<%= seed_page_archive %>

app/views/posts/new.html.erb
<div id="seed-admin-form">
  <h2 class="admin">Create blog post</h2>
  
  <div id="articlesform">
  	<%= render :partial => "form", :locals => {:submit => "Create"} %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post" id="post_<%= @post.id %>">
	
	<h2><%= @post.title %></h2>
	<h4>By <%= @post.author %>, <%= simple_date(@post.created_at) %></h4>
	
	<div id="images">
	  <% @post.images.each do |image| -%>
	  	<a href="<%= image.public_filename %>" class="lightview" rel="gallery[<%= @post.id %>]">
        <%= image_tag image.public_filename("#{@post.imagesize}") %>
      </a>
	  <% end -%>
	</div>
	
	<%= textilize(@post.content) %>
</div>

<% if editable?(@page) -%>
	<div id="edit-link-<%= @post.id %>" style="display:none">
		<div class="first"><%= link_to "edit", edit_post_path(@page, @post)%></div>
		<div><%= link_to "delete", post_path(@page, @post), :confirm => 'Delete this post?', :method => :delete %></div>
	</div>
  <script>
  	new Tip($("post_<%= @post.id %>").down('h2'), $("edit-link-<%= @post.id %>"), {style: 'seed-edit'});
  </script>
<% end -%>

<div id="comments">

    <% if !@post.comments.size.zero? %>
	  <h3>Comments (<%= @post.comments.approved.size %>)</h3>
	  <%= render :partial => "comment", :collection => @post.comments.approved %>
	  
	  <% if editable?(@page) -%>
	    <h3>Rejected Comments</h3>
	    <% form_tag destroy_multiple_comments_path(:page_id => params[:page_id], :postid => params[:id]), :method => :delete do %>
	      <table class="clean">
	      <% for comment in Comment.unapproved.recent(50) %>
	        <tr>
	         <td><%= check_box_tag "comment_ids[]", comment.id, true %></td>
	         <td><%= link_to_unless(comment.website.blank?, content_tag(:strong, comment.name), comment.website) -%></td>
	         <td><%=h truncate(comment.comment, 30) %></td>
	         <td><%= link_to "not spam", approve_comment_path(comment, :page_id => params[:page_id]), :confirm => "Are you sure?", :method => :put %></td>
	        </tr>
	      <% end -%>
	      </table>
	      <p><%= submit_tag "Destroy Checked" %></p>
	    <% end -%>
	  <% end -%>
	  <% end -%>

</div>

<% if @post.commentable? %>
  <%= render :partial => "commentform" %>
<% end -%>